var _util =require('util/index.js');

var _user={

	logout:function(success,error){
		_util.request({
			method:'get',
			url:'/user/logout',
			success:success,
			error:error
		})
	},
	login:function(data,success,error){
		_util.request({
			method:'post',
			url:'/user/login',
			data:data,
			success:success,
			error:error
		})
	},
	register:function(data,success,error){
		_util.request({
			method:'post',
			url:'/user/register',
			data:data,
			success:success,
			error:error
		})
	},
	updatePassword:function(data,success,error){
		_util.request({
			method:'post',
			url:'/user/updatePassword',
			data:data,
			success:success,
			error:error
		})
	},
	loadUserName:function(success,error){
		_util.request({
			method:'get',
			url:'/user/getUserName',
			success:success,
			error:error
		})
	},
	loadUserInfo:function(success,error){
		_util.request({
			method:'get',
			url:'/user/getUserInfo',
			success:success,
			error:error
		})
	},
	checkUserName:function(data,success,error){
		_util.request({
			method:'get',
			url:'/user/checkUsername',
			data:{
				username:data
			},
			success:success,
			error:error
		})
	}
} 
module.exports=_user