var _util =require('util/index.js');

var _cart={
	addCartGoods:function(data,success,error){
		_util.request({
			method:'post',
			url:'/cart',
			data:data,
			success:success,
			error:error
		})
	},
	getCart:function(success,error){
		_util.request({
			url:'/cart',
			success:success,
			error:error
		})
	},
	selectOne:function(data,success,error){
		_util.request({
			method:'put',
			url:'/cart/selectOne',
			data:data,
			success:success,
			error:error
		})
	},
	offSelectOne:function(data,success,error){
		_util.request({
			method:'put',
			url:'/cart/offSelectOne',
			data:data,
			success:success,
			error:error
		})
	},
	selectAll:function(success,error){
		_util.request({
			method:'put',
			url:'/cart/selectAll',
			success:success,
			error:error
		})
	},
	offSelectAll:function(success,error){
		_util.request({
			method:'put',
			url:'/cart/offSelectAll',
			success:success,
			error:error
		})
	},
	deleteOne:function(data,success,error){
		_util.request({
			method:'put',
			url:'/cart/deleteOne',
			data:data,
			success:success,
			error:error
		})
	},
	deleteSelected:function(success,error){
		_util.request({
			method:'put',
			url:'/cart/deleteSelected',
			success:success,
			error:error
		})
	},
	updateCount:function(data,success,error){
		_util.request({
			method:'put',
			url:'/cart/updateCount',
			data:data,
			success:success,
			error:error
		})
	},
	getCartInfo:function(success,error){
		_util.request({
			method:'get',
			url:'/cart/count',
			success:success,
			error:error
		})
	}
}

module.exports=_cart;